
package fr.s2re.banque.servicebanque;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceBanqueWebService", targetNamespace = "http://servicebanque.banque.s2re.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServiceBanqueWebService {


    /**
     * 
     * @param paramidCompte
     * @param paramMontant
     */
    @WebMethod
    @RequestWrapper(localName = "crediter", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.Crediter")
    @ResponseWrapper(localName = "crediterResponse", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.CrediterResponse")
    public void crediter(
        @WebParam(name = "paramidCompte", targetNamespace = "")
        Integer paramidCompte,
        @WebParam(name = "paramMontant", targetNamespace = "")
        Double paramMontant);

    /**
     * 
     * @param paramMontantCommande
     * @param paramIdCompte
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifierSolde", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.VerifierSolde")
    @ResponseWrapper(localName = "verifierSoldeResponse", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.VerifierSoldeResponse")
    public boolean verifierSolde(
        @WebParam(name = "paramIdCompte", targetNamespace = "")
        int paramIdCompte,
        @WebParam(name = "paramMontantCommande", targetNamespace = "")
        double paramMontantCommande);

    /**
     * 
     * @param paramidCompte
     * @return
     *     returns java.util.List<fr.s2re.banque.servicebanque.CarteBancaireDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCarteByCompte", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.GetCarteByCompte")
    @ResponseWrapper(localName = "getCarteByCompteResponse", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.GetCarteByCompteResponse")
    public List<CarteBancaireDto> getCarteByCompte(
        @WebParam(name = "paramidCompte", targetNamespace = "")
        Integer paramidCompte);

    /**
     * 
     * @param paramidCompte
     * @param paramMontant
     */
    @WebMethod
    @RequestWrapper(localName = "debiter", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.Debiter")
    @ResponseWrapper(localName = "debiterResponse", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.DebiterResponse")
    public void debiter(
        @WebParam(name = "paramidCompte", targetNamespace = "")
        Integer paramidCompte,
        @WebParam(name = "paramMontant", targetNamespace = "")
        Double paramMontant);

    /**
     * 
     * @param paramIdCompte
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSolde", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.GetSolde")
    @ResponseWrapper(localName = "getSoldeResponse", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.GetSoldeResponse")
    public double getSolde(
        @WebParam(name = "paramIdCompte", targetNamespace = "")
        Integer paramIdCompte);

    /**
     * 
     * @param paramIdClient
     * @return
     *     returns java.util.List<fr.s2re.banque.servicebanque.CompteBancaireDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompteByClient", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.GetCompteByClient")
    @ResponseWrapper(localName = "getCompteByClientResponse", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.GetCompteByClientResponse")
    public List<CompteBancaireDto> getCompteByClient(
        @WebParam(name = "paramIdClient", targetNamespace = "")
        Integer paramIdClient);

    /**
     * 
     * @param paramNom
     * @return
     *     returns fr.s2re.banque.servicebanque.ClientDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCLientByNom", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.GetCLientByNom")
    @ResponseWrapper(localName = "getCLientByNomResponse", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.GetCLientByNomResponse")
    public ClientDto getCLientByNom(
        @WebParam(name = "paramNom", targetNamespace = "")
        String paramNom);

}
